### ISSUE TITLE
Some questions.


### ISSUE THREAD

**Issue by europer** [aloishockenschlohe/sdm630-emulator-pymodbus#1]
Can you give some more input on how you use it. Do you use 

Waveshare Industrial USB to RS485... https://www.amazon.de/dp/B082D5PXJ4?ref=ppx_pop_mob_ap_share

Connected to you RaspberryPi to communicate with your Inverter?

What does the text file look like? 

I have a dtsu666 power meter what I can read the data in home assistant for my 1st inverter and my 2nd inverter, the deye is in the garage so I would like to emulate it for the deye, using the data from the home assistant so I can have zero to grid. 

Best regards
Per

**Comment by aloishockenschlohe** [comment]
If you have any more questions: you are welcome. :-)
